name: Auto Deploy Play Store

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Instalar Gradle (compatible con tu proyecto)
      - name: Install Gradle
        run: |
          sudo apt update
          sudo apt install -y gradle

      # 4. Generar gradlew automáticamente
      - name: Generate Wrapper
        run: gradle wrapper

      # 5. Instalar Fastlane
      - name: Install Fastlane
        run: sudo gem install fastlane

      # 6. Crear keystore (en raíz para evitar errores de ruta)
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release-key.jks

      # 7. Build
      - name: Build AAB
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew bundleRelease

      # 8. Deploy
      - name: Deploy to Play Store
        run: fastlane deploy
        env:
          GOOGLE_PLAY_JSON: ${{ secrets.GOOGLE_PLAY_JSON }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
